import React, { useState, useEffect } from 'react';
import {
  FileDown,
  FileCode2,
  FileText,
  ShieldCheck,
  Award,
  AlertTriangle,
  CheckCircle2,
  Network,
  Clock,
  Lock,
  Eye,
} from 'lucide-react';
import { ForensicCaseSummary } from '../types';

interface ForensicReportViewProps {
  activeCase: ForensicCaseSummary;
}

export const ForensicReportView: React.FC<ForensicReportViewProps> = ({
  activeCase,
}) => {
  const [reportData, setReportData] = useState<any | null>(null);
  const [loading, setLoading] = useState(false);
  const [showMarkdownPreview, setShowMarkdownPreview] = useState(false);

  useEffect(() => {
    let mounted = true;
    setLoading(true);
    fetch(`/api/v1/reports?caseId=${encodeURIComponent(activeCase.id)}`)
      .then((r) => r.json())
      .then((data) => {
        if (mounted) setReportData(data);
      })
      .finally(() => {
        if (mounted) setLoading(false);
      });
    return () => {
      mounted = false;
    };
  }, [activeCase.id]);

  return (
    <div className="space-y-6 pb-8">
      {/* Top Export Controls Bar */}
      <div className="bg-white border border-slate-200/90 rounded-2xl p-6 shadow-sm flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 border border-blue-200 text-blue-700 text-xs font-bold mb-2">
            <Award className="w-3.5 h-3.5" />
            <span>ISO/IEC 27037 &amp; NIST SP 800-86 Court-Admissible Dossier</span>
          </div>
          <h2 className="text-xl font-extrabold text-slate-900">
            Structured Forensic Incident Report — {activeCase.caseNumber}
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">
            Generated by the Java 21 Jakarta Servlet Forensic Report Engine with embedded SHA-256 &amp; BLAKE3 seals.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2.5">
          <a
            href={`/api/v1/reports/pdf?caseId=${encodeURIComponent(activeCase.id)}`}
            target="_blank"
            rel="noreferrer"
            className="px-4 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold flex items-center gap-2 shadow-sm transition"
          >
            <FileDown className="w-4 h-4" />
            <span>Download Court-Admissible PDF (%PDF-1.7)</span>
          </a>

          <a
            href={`/api/v1/reports/stix?caseId=${encodeURIComponent(
              activeCase.id
            )}`}
            target="_blank"
            rel="noreferrer"
            className="px-4 py-2.5 rounded-xl bg-white hover:bg-slate-50 border border-slate-200 text-slate-800 text-xs font-bold flex items-center gap-2 shadow-sm transition"
          >
            <FileCode2 className="w-4 h-4 text-purple-600" />
            <span>Export STIX 2.1 Threat Bundle (.json)</span>
          </a>

          <a
            href={`/api/v1/reports/markdown?caseId=${encodeURIComponent(
              activeCase.id
            )}`}
            target="_blank"
            rel="noreferrer"
            className="px-4 py-2.5 rounded-xl bg-white hover:bg-slate-50 border border-slate-200 text-slate-800 text-xs font-bold flex items-center gap-2 shadow-sm transition"
          >
            <FileText className="w-4 h-4 text-emerald-600" />
            <span>Download Markdown Brief (.md)</span>
          </a>

          <button
            onClick={() => setShowMarkdownPreview(!showMarkdownPreview)}
            className="px-3.5 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-bold flex items-center gap-1.5 transition"
          >
            <Eye className="w-3.5 h-3.5" />
            <span>{showMarkdownPreview ? 'Hide Markdown' : 'Raw Markdown'}</span>
          </button>
        </div>
      </div>

      {loading && (
        <div className="bg-white border border-slate-200 rounded-2xl p-8 text-center text-sm text-slate-500">
          Compiling cryptographic seals, timeline events, and entity correlations...
        </div>
      )}

      {showMarkdownPreview && reportData?.markdownPreview && (
        <div className="bg-slate-900 text-slate-100 rounded-2xl p-6 font-mono text-xs overflow-x-auto shadow-md">
          <div className="flex items-center justify-between text-slate-400 pb-3 mb-3 border-b border-slate-800">
            <span>Generated Forensic Markdown Dossier ({activeCase.caseNumber})</span>
            <span>UTF-8</span>
          </div>
          <pre className="whitespace-pre-wrap leading-relaxed text-[11px] text-emerald-300">
            {reportData.markdownPreview}
          </pre>
        </div>
      )}

      {reportData && (
        <div className="bg-white border border-slate-200/90 rounded-2xl p-8 shadow-sm space-y-7">
          {/* Formal Dossier Header */}
          <div className="border-b border-slate-200 pb-6 flex flex-wrap items-start justify-between gap-4">
            <div>
              <div className="text-xs font-mono uppercase tracking-widest text-blue-600 font-bold">
                CYBERFUSION X — OFFICIAL FORENSIC RECONSTRUCTION DOSSIER
              </div>
              <h1 className="text-2xl font-extrabold text-slate-900 mt-1">
                {activeCase.title}
              </h1>
              <div className="text-xs text-slate-500 mt-1.5">
                Case Number:{' '}
                <strong className="text-slate-800 font-mono">
                  {activeCase.caseNumber}
                </strong>{' '}
                · Lead Investigator:{' '}
                <strong className="text-slate-800">
                  {activeCase.leadInvestigatorName}
                </strong>{' '}
                · Victim:{' '}
                <strong className="text-slate-800">
                  {activeCase.victimName}
                </strong>{' '}
                · Quantified Exposure:{' '}
                <strong className="text-slate-900 font-mono">
                  ${activeCase.estimatedLossUsd.toLocaleString()}
                </strong>
              </div>
            </div>

            <div className="p-3.5 rounded-xl bg-emerald-50 border border-emerald-200 text-right">
              <div className="text-[10px] font-mono uppercase font-bold text-emerald-700 flex items-center justify-end gap-1">
                <ShieldCheck className="w-3.5 h-3.5" />
                HMAC-SHA256 Report Certificate
              </div>
              <div className="font-mono text-xs font-bold text-slate-900 mt-1">
                {reportData.digitalSignature
                  ? `${reportData.digitalSignature.slice(0, 28)}…`
                  : 'SHA-256 SEALED'}
              </div>
              <div className="text-[10px] font-mono text-slate-500 mt-0.5">
                Generated: {reportData.generatedAt}
              </div>
            </div>
          </div>

          {/* Section 1: Executive Summary & Risk Score */}
          <div className="space-y-2">
            <h3 className="text-sm font-extrabold uppercase tracking-wider text-slate-500">
              1. Executive Forensic Summary
            </h3>
            <p className="text-sm text-slate-700 leading-relaxed bg-slate-50 p-4 rounded-xl border border-slate-200/80">
              {activeCase.summary}
            </p>
          </div>

          {/* Section 2: Risk Indicators */}
          <div className="space-y-3">
            <h3 className="text-sm font-extrabold uppercase tracking-wider text-slate-500">
              2. Automated Risk Indicators &amp; MITRE ATT&amp;CK Flags (Composite Score: {reportData.riskScore ?? activeCase.riskScore}/100)
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {(reportData.riskIndicators || activeCase.riskIndicators || []).map(
                (flag: any, i: number) => (
                  <div
                    key={i}
                    className="p-3.5 rounded-xl bg-amber-50/70 border border-amber-200 flex items-start gap-2.5 text-xs text-slate-800"
                  >
                    <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
                    <div className="space-y-0.5">
                      <div className="font-bold text-slate-900">
                        {typeof flag === 'string' ? flag : flag.title}
                        {flag.mitreTechnique && (
                          <span className="ml-2 px-1.5 py-0.2 rounded bg-white border border-amber-300 font-mono text-[10px] text-amber-800">
                            {flag.mitreTechnique}
                          </span>
                        )}
                      </div>
                      {typeof flag !== 'string' && flag.description && (
                        <div className="text-slate-600 leading-relaxed">
                          {flag.description}
                        </div>
                      )}
                    </div>
                  </div>
                )
              )}
            </div>
          </div>

          {/* Section 3: Sealed Evidence Manifest */}
          {reportData.evidenceManifest && (
            <div className="space-y-3">
              <h3 className="text-sm font-extrabold uppercase tracking-wider text-slate-500">
                3. Cryptographic Evidence Manifest (SHA-256 &amp; BLAKE3)
              </h3>
              <div className="overflow-x-auto border border-slate-200 rounded-xl">
                <table className="w-full text-left border-collapse text-xs">
                  <thead>
                    <tr className="bg-slate-50 border-b border-slate-200 text-[11px] font-bold uppercase text-slate-500">
                      <th className="py-2.5 px-3">Code</th>
                      <th className="py-2.5 px-3">Artifact Filename</th>
                      <th className="py-2.5 px-3">Category</th>
                      <th className="py-2.5 px-3">SHA-256 Digest</th>
                      <th className="py-2.5 px-3">BLAKE3 Digest</th>
                      <th className="py-2.5 px-3">Status</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {reportData.evidenceManifest.map((ev: any) => (
                      <tr key={ev.id}>
                        <td className="py-2.5 px-3 font-mono font-bold text-blue-600">
                          {ev.evidenceCode}
                        </td>
                        <td className="py-2.5 px-3 font-semibold text-slate-900">
                          {ev.originalFilename}
                        </td>
                        <td className="py-2.5 px-3 text-slate-600">
                          {ev.evidenceCategory}
                        </td>
                        <td className="py-2.5 px-3 font-mono text-[11px] text-slate-600">
                          {ev.sha256Hash?.slice(0, 20)}…
                        </td>
                        <td className="py-2.5 px-3 font-mono text-[11px] text-slate-600">
                          {ev.blake3Hash?.slice(0, 20)}…
                        </td>
                        <td className="py-2.5 px-3">
                          <span
                            className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full font-bold text-[10px] border ${
                              ev.integrityStatus === 'VERIFIED_INTACT'
                                ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
                                : 'bg-red-50 text-red-700 border-red-200'
                            }`}
                          >
                            <CheckCircle2 className="w-3 h-3" />
                            {ev.integrityStatus}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Section 4: Correlated Entities & Centrality Scores */}
          {reportData.entities && (
            <div className="space-y-3">
              <h3 className="text-sm font-extrabold uppercase tracking-wider text-slate-500 flex items-center gap-2">
                <Network className="w-4 h-4 text-blue-600" />
                <span>
                  4. Correlated Forensic Entities &amp; Graph Centrality ({reportData.entities.length} IOCs)
                </span>
              </h3>
              <div className="overflow-x-auto border border-slate-200 rounded-xl">
                <table className="w-full text-left border-collapse text-xs">
                  <thead>
                    <tr className="bg-slate-50 border-b border-slate-200 text-[11px] font-bold uppercase text-slate-500">
                      <th className="py-2.5 px-3">Entity Label</th>
                      <th className="py-2.5 px-3">Type</th>
                      <th className="py-2.5 px-3">Role in Incident</th>
                      <th className="py-2.5 px-3">PageRank</th>
                      <th className="py-2.5 px-3">Risk Level</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {reportData.entities.slice(0, 10).map((ent: any) => (
                      <tr key={ent.id}>
                        <td className="py-2.5 px-3 font-mono font-bold text-slate-900">
                          {ent.displayLabel}
                        </td>
                        <td className="py-2.5 px-3">
                          <span className="px-2 py-0.5 rounded bg-blue-50 text-blue-700 font-mono text-[10px] font-bold">
                            {ent.entityType}
                          </span>
                        </td>
                        <td className="py-2.5 px-3 text-slate-600">
                          {ent.roleInIncident}
                        </td>
                        <td className="py-2.5 px-3 font-mono text-slate-700">
                          {((ent.pagerankScore || 0) * 100).toFixed(1)}%
                        </td>
                        <td className="py-2.5 px-3">
                          <span
                            className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${
                              ent.riskLevel === 'CRITICAL'
                                ? 'bg-red-50 text-red-700 border border-red-200'
                                : ent.riskLevel === 'HIGH'
                                ? 'bg-orange-50 text-orange-700 border border-orange-200'
                                : 'bg-slate-100 text-slate-700'
                            }`}
                          >
                            {ent.riskLevel}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Section 5: Reconstructed Kill-Chain Timeline & Chain-of-Custody Seal */}
          {reportData.timeline && (
            <div className="space-y-3">
              <h3 className="text-sm font-extrabold uppercase tracking-wider text-slate-500 flex items-center gap-2">
                <Clock className="w-4 h-4 text-teal-600" />
                <span>
                  5. Chronological Kill-Chain Reconstruction ({reportData.timeline.length} Milestones)
                </span>
              </h3>
              <div className="space-y-2">
                {reportData.timeline.map((ev: any) => (
                  <div
                    key={ev.id}
                    className="p-3 rounded-xl bg-slate-50 border border-slate-200/80 flex flex-wrap items-center justify-between gap-2 text-xs"
                  >
                    <div className="flex items-center gap-2.5">
                      <span className="font-mono text-[11px] font-bold text-teal-700">
                        {ev.eventTimestamp}
                      </span>
                      <span className="px-2 py-0.5 rounded bg-white border border-slate-200 font-mono text-[10px] font-bold text-slate-700">
                        {ev.killChainPhase}
                      </span>
                      <span className="font-bold text-slate-900">
                        {ev.title}
                      </span>
                    </div>
                    {ev.anomalyFlag && (
                      <span className="px-2 py-0.5 rounded bg-red-50 text-red-700 border border-red-200 text-[10px] font-bold">
                        EXIF Timestamp Anomaly
                      </span>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Footer Custody Attestation */}
          <div className="pt-4 border-t border-slate-200 flex flex-wrap items-center justify-between gap-3 text-xs text-slate-500">
            <span className="flex items-center gap-1.5 font-semibold text-slate-700">
              <Lock className="w-4 h-4 text-emerald-600" />
              Chain-of-Custody Merkle Ledger Attested ({reportData.custodyLedger?.length || 0} Blocks)
            </span>
            <span className="font-mono text-[11px]">
              Signature: {reportData.digitalSignature}
            </span>
          </div>
        </div>
      )}
    </div>
  );
};
